# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15bcc4de583060f5145fc0b7e7c5270d8d672da3d55a278615914e276253275e6d0509941c9d5cfa7c9c2a7e3be93afb4145fabc158137feadf1eabbe805220b

test:
  secret_key_base: 3e192a361464621ce25fdf2411582601015c6c45aed750414d2e6e4fa916e6b45d30a93fcad8056754b660d4696499e6abe3aadcfd1b141945a24ffed16f93db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
